### ISSUE TITLE
version 2.3 not working in n++ 8.3.2

### ISSUE THREAD

**Issue by AlexZanini70** [DominicTobias/SecurePad#13]
it is not listed under the plugin menu despite being installed. tried to uninstall/install without luck.

**Comment by Tamarindo94** [comment]
Happens to me, too

**Comment by chcg** [comment]
Indeed with #12 plugindefinition files where overwritten with the plugintemplate versions instead of merging them.

**Comment by chcg** [comment]
Fixed with https://github.com/DominicTobias/SecurePad/releases/tag/v2.4 .
