### ISSUE TITLE
64-Bit binary 

### ISSUE THREAD

**Issue by CHEF-KOCH** [DominicTobias/SecurePad#4]
I guess we should provide an x86 (current) + an 64-bit binary.

**Comment by DominicTobias** [comment]
Hi this makes sense and your other issue. However I don't have Windows anymore, so if you have any drive to make changes please be my guest!

**Comment by Neustradamus** [comment]
+1 for x86 + x64 in https://github.com/DominicTobias/SecurePad/releases
