### ISSUE TITLE
Version in bin

### ISSUE THREAD

**Issue by Gitoffthelawn** [DominicTobias/SecurePad#6]
Just to be clear, the version at https://github.com/DominicTobias/SecurePad/tree/master/bin is really version 2.2, but just has the incorrect version information in the `Resources.rc` file (which we now fixed, but has not been rebuilt).

Is my understanding correct?

**Comment by dominictobias** [comment]
Hi yes, the problem is that I'm not on windows anymore and don't have an environment set up for compiling it 😜 I've been meaning to set up a virtual windows for some time but haven't got round to it #lazy. If you have any inclination please feel free to do so!

**Comment by Gitoffthelawn** [comment]
No problem.  You may want to check out https://www.appveyor.com/

In any case, #irespectyourlaziness ;)

**Comment by chcg** [comment]
See release https://github.com/DominicTobias/SecurePad/releases/tag/v2.2 with this change included.

**Comment by dominictobias** [comment]
@chcg niice! thanks
