### ISSUE TITLE
Stopped working on Notepad++ version 7.6

### ISSUE THREAD

**Issue by havilson** [DominicTobias/SecurePad#8]
Hi, I use your work for several years. Right now Notepad++ changed the way it manages plugins. Is it possible to fix it? Thanks anyway.

Havilson

**Comment by dominictobias** [comment]
Hi @havilson, unfortunately I don't even have a Windows desktop anymore so fixing it is unlikely! Hopefully someone who does can make a PR

**Comment by havilson** [comment]
Thanks @DominicTobias for your answer, let's hope someone could help. :)

**Comment by chcg** [comment]
@havilson Most likely you are just facing the issue described here:
https://notepad-plus-plus.org/news/notepad-7.6-released.html

> FOR PLUGIN USERS:
> to remedy this problem, after the update, you can :
> Find the name of plugin you want to migrate in %PROGRAMFILES(x86)%\Notepad++\plugins\myAwesomePlugin.dll (or %PROGRAMFILES%\Notepad++\plugins\myAwesomePlugin.dll, according the achetecture of your Notepad++).
> go to %LOCALAPPDATA%\Notepad++\plugins\ to create myAwesomePlugin folder.
> move the plungin myAwesomePlugin.dll from %PROGRAMFILES(x86)%\Notepad++\plugins\ to %LOCALAPPDATA%\Notepad++\plugins\myAwesomePlugin\.
> That’s it. Restart Notepad++ and you get your beloved plugins back.
> 
> 

Is the plugin working again after moving it to the new plugin directory under the subfolder SecurePad?

**Comment by chcg** [comment]
Added to plugin admin list with https://github.com/notepad-plus-plus/nppPluginList/commit/b7d6801aa00187bb431313b0b3ee123f50e3ab2e.

**Comment by havilson** [comment]
@chcg worked like a charm, should have read it before. Thanks anyway!
